### ISSUE TITLE
Event scheduler web UI text on Daily Events tab

### ISSUE THREAD

**Issue by cyberbri24** [CeneroLLC/Cenero-App-Kit-Docs#21]
![thrusday-text](https://github.com/CeneroLLC/Cenero-App-Kit-Docs/assets/83354743/068ad040-5812-4792-a139-012adcd8494f)

noticed this today. not a big deal.
just a text item to add to the bucket list one day.. thrusday

**Comment by ewilliams0305** [comment]
Nice catch, appreciate it
